// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ9lUJef9Xa0elYa-TeqMNAj62nCNWJu8',
    appId: '1:69199111588:web:3ff989c35f71620304cd31',
    messagingSenderId: '69199111588',
    projectId: 'the-bowler-328c7',
    authDomain: 'the-bowler-328c7.firebaseapp.com',
    storageBucket: 'the-bowler-328c7.appspot.com',
    measurementId: 'G-1TSL93DE6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHM8OXvsybZIOTkheHXztFSbqXqHQCVlY',
    appId: '1:69199111588:android:e4a86b9222ffab5304cd31',
    messagingSenderId: '69199111588',
    projectId: 'the-bowler-328c7',
    storageBucket: 'the-bowler-328c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJNLUJoITy9f7z3YTkP0Fr1cbAP0iPU58',
    appId: '1:69199111588:ios:2bfcdf8d37d7fd2d04cd31',
    messagingSenderId: '69199111588',
    projectId: 'the-bowler-328c7',
    storageBucket: 'the-bowler-328c7.appspot.com',
    iosBundleId: 'com.example.motorControllerEsp32',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJNLUJoITy9f7z3YTkP0Fr1cbAP0iPU58',
    appId: '1:69199111588:ios:7a809230841d945004cd31',
    messagingSenderId: '69199111588',
    projectId: 'the-bowler-328c7',
    storageBucket: 'the-bowler-328c7.appspot.com',
    iosBundleId: 'com.example.motorControllerEsp32.RunnerTests',
  );
}
